# Generated by Django 3.1.7 on 2021-04-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IssueArea',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('num_practices', models.IntegerField(default=7)),
                ('intro_text', models.TextField(blank=True, default='', null=True)),
                ('conclusion_text', models.TextField(blank=True, default='', null=True)),
                ('practice_1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('practice_1_question', models.TextField(blank=True, default='', null=True)),
                ('practice_1_description', models.TextField(blank=True, default='', null=True)),
                ('practice_1_quote', models.TextField(blank=True, default='', null=True)),
                ('practice_1_link', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('practice_2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('practice_2_question', models.TextField(blank=True, default='', null=True)),
                ('practice_2_description', models.TextField(blank=True, default='', null=True)),
                ('practice_2_quote', models.TextField(blank=True, default='', null=True)),
                ('practice_2_link', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('practice_3', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('practice_3_question', models.TextField(blank=True, default='', null=True)),
                ('practice_3_description', models.TextField(blank=True, default='', null=True)),
                ('practice_3_quote', models.TextField(blank=True, default='', null=True)),
                ('practice_3_link', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('practice_4', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('practice_4_question', models.TextField(blank=True, default='', null=True)),
                ('practice_4_description', models.TextField(blank=True, default='', null=True)),
                ('practice_4_quote', models.TextField(blank=True, default='', null=True)),
                ('practice_4_link', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('practice_5', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('practice_5_question', models.TextField(blank=True, default='', null=True)),
                ('practice_5_description', models.TextField(blank=True, default='', null=True)),
                ('practice_5_quote', models.TextField(blank=True, default='', null=True)),
                ('practice_5_link', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('practice_6', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('practice_6_question', models.TextField(blank=True, default='', null=True)),
                ('practice_6_description', models.TextField(blank=True, default='', null=True)),
                ('practice_6_quote', models.TextField(blank=True, default='', null=True)),
                ('practice_6_link', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('practice_7', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('practice_7_question', models.TextField(blank=True, default='', null=True)),
                ('practice_7_description', models.TextField(blank=True, default='', null=True)),
                ('practice_7_quote', models.TextField(blank=True, default='', null=True)),
                ('practice_7_link', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(default='', max_length=3)),
                ('population', models.IntegerField()),
                ('county_administered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_1', models.CharField(choices=[('1', 'Implemented'), ('0', 'Not Implemented'), ('2', 'In Progress'), ('-1', 'No Data')], max_length=20)),
                ('practice_2', models.CharField(choices=[('1', 'Implemented'), ('0', 'Not Implemented'), ('2', 'In Progress'), ('-1', 'No Data')], max_length=20)),
                ('practice_3', models.CharField(choices=[('1', 'Implemented'), ('0', 'Not Implemented'), ('2', 'In Progress'), ('-1', 'No Data')], max_length=20)),
                ('practice_4', models.CharField(choices=[('1', 'Implemented'), ('0', 'Not Implemented'), ('2', 'In Progress'), ('-1', 'No Data')], max_length=20)),
                ('practice_5', models.CharField(choices=[('1', 'Implemented'), ('0', 'Not Implemented'), ('2', 'In Progress'), ('-1', 'No Data')], max_length=20)),
                ('practice_6', models.CharField(choices=[('1', 'Implemented'), ('0', 'Not Implemented'), ('2', 'In Progress'), ('-1', 'No Data')], max_length=20)),
                ('practice_7', models.CharField(choices=[('1', 'Implemented'), ('0', 'Not Implemented'), ('2', 'In Progress'), ('-1', 'No Data')], max_length=20)),
                ('issue_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina_app.issuearea')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina_app.state')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('position', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('issue_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina_app.issuearea')),
            ],
        ),
    ]
