# Generated by Django 3.1.7 on 2021-04-12 15:18

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementation',
            name='subpractices_1',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('1', 'Implemented'), ('0', 'Not Implemented'), ('2', 'In Progress'), ('-1', 'No Data')], max_length=20), blank=True, max_length=63, null=True, size=3),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractices_2',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('1', 'Implemented'), ('0', 'Not Implemented'), ('2', 'In Progress'), ('-1', 'No Data')], max_length=20), blank=True, max_length=63, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_1_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=200), blank=True, max_length=602, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_2_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=200), blank=True, max_length=602, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_3_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=200), blank=True, max_length=602, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_4_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=200), blank=True, max_length=602, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_5_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=200), blank=True, max_length=602, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_6_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=200), blank=True, max_length=602, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_7_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=200), blank=True, max_length=602, null=True, size=3),
        ),
    ]
