# Generated by Django 3.1.7 on 2021-04-19 21:34

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('body', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractices_1',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Null', 'Null')], max_length=5), blank=True, max_length=18, null=True, size=3),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractices_2',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Null', 'Null')], max_length=5), blank=True, max_length=18, null=True, size=3),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractices_3',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Null', 'Null')], max_length=5), blank=True, max_length=18, null=True, size=3),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractices_4',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Null', 'Null')], max_length=5), blank=True, max_length=18, null=True, size=3),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractices_5',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Null', 'Null')], max_length=5), blank=True, max_length=18, null=True, size=3),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractices_6',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Null', 'Null')], max_length=5), blank=True, max_length=18, null=True, size=3),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractices_7',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Null', 'Null')], max_length=5), blank=True, max_length=18, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='num_subpractices_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='num_subpractices_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='num_subpractices_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='num_subpractices_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='num_subpractices_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='num_subpractices_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='num_subpractices_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_1_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_2_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_3_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_4_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_5_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_6_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_7_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=302, null=True, size=3),
        ),
    ]
