# Generated by Django 3.1.7 on 2021-04-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementation',
            name='practice_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_2',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_3',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_4',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_5',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_6',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_7',
            field=models.BooleanField(null=True),
        ),
    ]
