# Generated by Django 3.1.7 on 2021-04-12 15:22

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0002_auto_20210412_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementation',
            name='practice_1',
            field=models.CharField(choices=[('Implemented', 'Implemented'), ('Not Implemented', 'Not Implemented'), ('In Progress', 'In Progress'), ('No Data', 'No Data')], max_length=20),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_2',
            field=models.CharField(choices=[('Implemented', 'Implemented'), ('Not Implemented', 'Not Implemented'), ('In Progress', 'In Progress'), ('No Data', 'No Data')], max_length=20),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_3',
            field=models.CharField(choices=[('Implemented', 'Implemented'), ('Not Implemented', 'Not Implemented'), ('In Progress', 'In Progress'), ('No Data', 'No Data')], max_length=20),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_4',
            field=models.CharField(choices=[('Implemented', 'Implemented'), ('Not Implemented', 'Not Implemented'), ('In Progress', 'In Progress'), ('No Data', 'No Data')], max_length=20),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_5',
            field=models.CharField(choices=[('Implemented', 'Implemented'), ('Not Implemented', 'Not Implemented'), ('In Progress', 'In Progress'), ('No Data', 'No Data')], max_length=20),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_6',
            field=models.CharField(choices=[('Implemented', 'Implemented'), ('Not Implemented', 'Not Implemented'), ('In Progress', 'In Progress'), ('No Data', 'No Data')], max_length=20),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_7',
            field=models.CharField(choices=[('Implemented', 'Implemented'), ('Not Implemented', 'Not Implemented'), ('In Progress', 'In Progress'), ('No Data', 'No Data')], max_length=20),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='subpractices_1',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('Implemented', 'Implemented'), ('Not Implemented', 'Not Implemented'), ('In Progress', 'In Progress'), ('No Data', 'No Data')], max_length=20), blank=True, max_length=63, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='subpractices_2',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('Implemented', 'Implemented'), ('Not Implemented', 'Not Implemented'), ('In Progress', 'In Progress'), ('No Data', 'No Data')], max_length=20), blank=True, max_length=63, null=True, size=3),
        ),
    ]
