# Generated by Django 3.1.7 on 2021-04-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0002_auto_20210419_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementation',
            name='practice_1',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_2',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_3',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_4',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_5',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_6',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='practice_7',
            field=models.NullBooleanField(),
        ),
    ]
