# Generated by Django 3.1.7 on 2021-03-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0002_auto_20210301_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='bestPractices',
        ),
        migrations.AddField(
            model_name='state',
            name='bestPractice1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='bestPractice2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='bestPractice3',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='BestPractice',
        ),
    ]
