# Generated by Django 3.1.7 on 2021-04-19 22:57

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0004_auto_20210419_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementation',
            name='subpractice_1_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_1_2',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_1_3',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_2_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_2_2',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_2_3',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_3_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_3_2',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_3_3',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_4_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_4_2',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_4_3',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_5_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_5_2',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_5_3',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_6_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_6_2',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_6_3',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_7_1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_7_2',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='implementation',
            name='subpractice_7_3',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='num_subpractices_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='num_subpractices_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='num_subpractices_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='num_subpractices_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='num_subpractices_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='num_subpractices_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='num_subpractices_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_1_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_2_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_3_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_4_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_5_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_6_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='subpractices_7_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=302, null=True, size=3),
        ),
    ]
