# Generated by Django 3.1.7 on 2021-03-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0004_auto_20210304_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(default='', max_length=3),
        ),
    ]
