# Generated by Django 3.1.7 on 2021-04-20 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0005_auto_20210419_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuearea',
            old_name='practice_1_quote',
            new_name='practice_1_example',
        ),
        migrations.RenameField(
            model_name='issuearea',
            old_name='practice_2_quote',
            new_name='practice_2_example',
        ),
        migrations.RenameField(
            model_name='issuearea',
            old_name='practice_3_quote',
            new_name='practice_3_example',
        ),
        migrations.RenameField(
            model_name='issuearea',
            old_name='practice_4_quote',
            new_name='practice_4_example',
        ),
        migrations.RenameField(
            model_name='issuearea',
            old_name='practice_5_quote',
            new_name='practice_5_example',
        ),
        migrations.RenameField(
            model_name='issuearea',
            old_name='practice_6_quote',
            new_name='practice_6_example',
        ),
        migrations.RenameField(
            model_name='issuearea',
            old_name='practice_7_quote',
            new_name='practice_7_example',
        ),
    ]
