# Generated by Django 3.1.7 on 2021-03-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0005_state_abbreviation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='office_contact',
            new_name='county_administered',
        ),
        migrations.AddField(
            model_name='state',
            name='no_contact',
            field=models.BooleanField(default=False),
        ),
    ]
