# Generated by Django 3.1.7 on 2021-04-23 13:35

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0006_auto_20210419_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuearea',
            name='subpractices_1_names',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=100, null=True), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='subpractices_2_names',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=100, null=True), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='subpractices_3_names',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=100, null=True), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='subpractices_4_names',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=100, null=True), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='subpractices_5_names',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=100, null=True), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='subpractices_6_names',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=100, null=True), blank=True, max_length=302, null=True, size=3),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='subpractices_7_names',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=100, null=True), blank=True, max_length=302, null=True, size=3),
        ),
    ]
