# Generated by Django 3.1.7 on 2021-03-31 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0006_auto_20210311_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuearea',
            name='id',
        ),
        migrations.RemoveField(
            model_name='issuearea',
            name='states',
        ),
        migrations.RemoveField(
            model_name='state',
            name='electronic_request',
        ),
        migrations.RemoveField(
            model_name='state',
            name='id',
        ),
        migrations.RemoveField(
            model_name='state',
            name='no_contact',
        ),
        migrations.RemoveField(
            model_name='state',
            name='no_fee',
        ),
        migrations.RemoveField(
            model_name='state',
            name='no_notary_required',
        ),
        migrations.RemoveField(
            model_name='state',
            name='no_witness_required',
        ),
        migrations.AddField(
            model_name='issuearea',
            name='conclusion_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='intro_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_1_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_2_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_3_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_4_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_5',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_5_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_6',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_6_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_7',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_7_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_1', models.BooleanField(default=None)),
                ('practice_2', models.BooleanField(default=None)),
                ('practice_3', models.BooleanField(default=None)),
                ('practice_4', models.BooleanField(default=None)),
                ('practice_5', models.BooleanField(default=None)),
                ('practice_6', models.BooleanField(default=None)),
                ('practice_7', models.BooleanField(default=None)),
                ('issue_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina_app.issuearea')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina_app.state')),
            ],
        ),
    ]
