# Generated by Django 3.1.7 on 2021-04-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0007_auto_20210331_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuearea',
            name='num_practices',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_1_link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_2_link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_3_link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_4_link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_5_link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_6_link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_7_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
