# Generated by Django 3.1.7 on 2021-03-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0008_auto_20210327_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConclusionText',
        ),
        migrations.DeleteModel(
            name='IntroductionText',
        ),
        migrations.AddField(
            model_name='issuearea',
            name='conclusion_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='introduction_text',
            field=models.TextField(default=''),
        ),
    ]
