# Generated by Django 3.1.7 on 2021-04-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0008_auto_20210403_2240'),
        ('marina_app', '0009_auto_20210331_0251'),
    ]

    operations = [
    ]
