# Generated by Django 3.1.7 on 2021-04-05 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0010_merge_20210405_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('position', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='ImplementationGuidance',
        ),
        migrations.RemoveField(
            model_name='issuearea',
            name='introduction_text',
        ),
        migrations.AddField(
            model_name='contact',
            name='issue_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marina_app.issuearea'),
        ),
    ]
