# Generated by Django 3.1.7 on 2021-04-05 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0010_merge_20210405_1243'),
    ]

    operations = [

    ]
