# Generated by Django 3.1.7 on 2021-04-08 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0011_auto_20210405_1439'),
    ]

    operations = [
    ]
