# Generated by Django 3.1.7 on 2021-04-08 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0012_merge_20210407_2249'),
        ('marina_app', '0011_auto_20210405_2138'),
    ]

    operations = [
    ]
