# Generated by Django 3.1.7 on 2021-04-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0014_issuearea_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuearea',
            name='test',
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_1_question',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_1_quote',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_2_question',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_2_quote',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_3_question',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_3_quote',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_4_question',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_4_quote',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_5_question',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_5_quote',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_6_question',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_6_quote',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_7_question',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='issuearea',
            name='practice_7_quote',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='conclusion_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='intro_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_1_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_1_link',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_2_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_2_link',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_3',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_3_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_3_link',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_4',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_4_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_4_link',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_5',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_5_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_5_link',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_6',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_6_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_6_link',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_7',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_7_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='issuearea',
            name='practice_7_link',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
