# Generated by Django 3.1.7 on 2021-04-09 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marina_app', '0015_auto_20210407_2307'),
        ('marina_app', '0012_auto_20210406_1004'),
    ]

    operations = [
    ]
